#!/bin/bash

# Config File.

# Manual Resolution Support.
WIDTH="800"; HEIGHT="600";
export WIDTH HEIGHT

echo -e "\nm0n: ${WIDTH}x${HEIGHT}\n"

#
# Shell hardening, Signal trapping e handling
# Interactive shell locking and Secure restricted shell.
#
shellx() {
  # trap de signals.
  # FIX inicio com espacos + letras, control D.
  trap '' SIGINT
  trap '' SIGTSTP
  trap '' SIGQUIT
  trap '' SIGTERM

  while true; do
    read -rp "armx > " ID
      if [[ "$ID" = "q!" ]]; then
        echo $ID
	  exit
        elif [[ "$ID" =~ ^[a-zA-Z]+$ ]]; then
          break
        else
          echo "bye!"
	  exit
      fi

      done
      trap - SIGINT SIGTSTP SIGQUIT SIGTERM
}

#
# Compiler.
#
# https://mirrors.edge.kernel.org/pub/tools/crosstool
# https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/11.1.0/
# https://releases.linaro.org/components/toolchain/binaries/
# https://developer.arm.com/downloads/-/gnu-rm
#
MIRROR_LINARO="https://releases.linaro.org/components/toolchain/binaries/";
HARD_FLOAT="/arm-linux-gnueabihf/";
HARD_FLOAT_ARCH='x86.*_arm-linux-gnueabihf.tar.xz"';
GCC_BUILD_NAME="code-compiler"

#
# Bootloader.
#
# https://gitlab.com/u-boot/u-boot.git
# https://source.denx.de/u-boot/u-boot
# https://git.beagleboard.org/beagleboard/u-boot.git
#
MIRROR_UBOOT="https://gitlab.com/u-boot/u-boot.git"
UBOOT_BUILD_NAME="code-uboot"

#
# Kernel.
# 
# https://github.com/RobertCNelson/bb-kernel
# https://github.com/torvalds/linux
# https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
#
MIRROR_KERNEL="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
KERNEL_BUILD_NAME="code-kernel"

#
# Root File System.
#
# https://rcn-ee.com/rootfs/eewiki/minfs/
#
MIRROR_FS="https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/armhf/"
RTFS_BUILD_NAME="src-rootfs"

shellx