#!/bin/bash

echo -e "beaglebone-tool: xbuild version:cyrax\n"

# ARM Tool Beaglebone Black.
read -p "Project Name: " ID

# backup project into home folder.
backup_project(){
  tar -cf $ID-$(date +%d-%m)-bkp.tar.gz .build_$ID
  mv *-bkp.tar.gz $HOME
}

# check project name.
if [ -d .*_${ID} ]; then
  cd .*_${ID}
else
  mkdir -p .build_$ID && cd .*_${ID}
fi

# Project source.
DIR_BUILD=.build_${ID}

# Resolution support execute: xwininfo -stats -root.
WIDTH="1920"; HEIGHT="1080";

# Linaro Toolchain GCC (gnueabihf).
MIRROR_LINARO="https://releases.linaro.org/components/toolchain/binaries/";
HARD_FLOAT="/arm-linux-gnueabihf/";
HARD_FLOAT_ARCH='*x86.*_arm-linux-gnueabihf.tar.xz"';

# U-Boot.
MIRROR_UBOOT="https://source.denx.de/u-boot/u-boot.git"

# File System.
MIRROR_FS="https://rcn-ee.com/rootfs/eewiki/minfs/"

# Kernel.
MIRROR_KERNEL="https://github.com/torvalds/linux"

# Compilador!
compilador(){
  pkglist=""
  versions=$(curl -s "$MIRROR_LINARO"|grep binaries|sed -e "s/<a href=\"\/components\/toolchain\/binaries\///g"|sed 's/\/"//g'|sort)

  for pkg in $versions;
    do pkglist="$pkglist FALSE $pkg";
  done

  compiladores=`zenity --title="GCC Compiler List"\
		       --width=$WIDTH\
                       --height=$HEIGHT\
                       --text="Choose item:"\
                       --list\
                       --column="Selected"\
		       --column="Linaro Toolchain Package"\
                       --radiolist $pkglist\
                       --ok-label="Build Source"\
                       --cancel-label="Back"`

  # check bash special variable!
  if [ $? -eq 0 ]; then
    for VERSION in $compiladores; do

        # scrapping shell.
        GCC=$(curl -s "$MIRROR_LINARO$VERSION$HARD_FLOAT"|grep -E "$HARD_FLOAT_ARCH")
	GCC=$(echo $GCC|sed -e "s/<a href=\"\/components\/toolchain\/binaries\/"$VERSION"\/arm-linux-gnueabihf//g")
	GCC=${GCC:1:-1};

	# download compiler.
        echo -e "\n[GCC] Download GCC ARM Compiler -> "$VERSION"\n"
        curl $MIRROR_LINARO$VERSION$HARD_FLOAT$GCC -L -O

	# extract compiler.
        echo -e "\n[GCC] Extract GCC ARM Compiler -> "$GCC""
        tar -xf $GCC && BINARY=$(ls -d gcc*arm-linux-gnueabihf)

        # update bash profile(GCC) & test ${CC}gcc --version
        echo "CC=$PWD/$BINARY/bin/arm-linux-gnueabihf-" >> ~/.bash_profile && . ~/.bash_profile
        ${CC}gcc --version|grep $VERSION
    done
    else
      echo "Invalid Version!"
  fi
}

# Universal Bootloader (U-Boot).
bootloader(){
  git remote add master $MIRROR_UBOOT
  git remote -v
  tag_list=$(git ls-remote --tags $MIRROR_UBOOT|awk '{gsub("refs/tags/", "");print $2}'|grep "v.*[^}]$"|sort)
  choices=`zenity --title="Universal Bootloader List"\
                  --width=$WIDTH\
		  --height=$HEIGHT\
                  --text="Choose item:"\
                  --list\
                  --column="Selected"\
                  --column="U-Boot Tag Version"\
                  --radiolist $tag_list`
}

# Linux Kernel with LLRP Module.
kernel(){
  git remote add master $MIRROR_KERNEL
  git remote -v
  tag_list=$(git ls-remote --tags $MIRROR_KERNEL|awk '{gsub("refs/tags/", "");print $2}'|grep "v.*[^}]$"|sort)
  kernel_versions=${tag_list::-3}
  choices=`zenity --title="Linux Kernel List"\
                  --width=$WIDTH\
                  --height=$HEIGHT\
                  --text="Choose item:"\
                  --list\
                  --column="Selected"\
                  --column="U-Boot Tag Version"\
                  --radiolist $kernel_versions`
}

# Root File System.
file_system(){
  FS_VERSIONS=$(curl -s $MIRROR_FS|sed -nr 's/(.*)href="?([^ ">]*).*/\2\n\1/; T; P; D;')
  choices=`zenity --title="Root File System List"\
                  --width=$WIDTH\
                  --height=$HEIGHT\
                  --text="Choose item:"\
                  --list --column="Selected"\
                  --column="Root File System"\
                  --radiolist $FS_VERSIONS`
}

# Beaglebone Black Main xbuild.
while true;
do
  main=`zenity --title="Build ARM Image for Beaglebone Black."\
               --width=$WIDTH\
	       --height=$HEIGHT\
               --list\
	       --column="Configure Packages:"\
                               "ARM Cross Compiler: GCC"\
                               "Bootloader: U-Boot"\
                               "Linux Kernel"\
                               "Root File System"\
  			       "Setup microSD card"\
                               "Install Kernel and Root File System"`

  case "${main}" in
  "ARM Cross Compiler: GCC") compilador;;
  "Bootloader: U-Boot") bootloader;;
  "Linux Kernel") kernel;;
  "Root File System") file_system;;
  "Setup microSD card") sdcard_build;;
  "Install Kernel and Root File System") build;;
  *)
  exit 1
 esac
done
