#!/bin/bash

#
# Resolution Support.
#
# * xwininfo -stats -root
#
WIDTH="1920";
HEIGHT="1080";

#
# ARM Compiler.
#
# * https://mirrors.edge.kernel.org/pub/tools/crosstool
# * https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/11.1.0/
#
MIRROR_LINARO="https://releases.linaro.org/components/toolchain/binaries/";
HARD_FLOAT="/arm-linux-gnueabihf/";
HARD_FLOAT_ARCH='*x86.*_arm-linux-gnueabihf.tar.xz"';
GCC_BUILD_NAME="code-compiler"

#
# Bootloader.
#
# * https://gitlab.com/u-boot/u-boot.git
# * https://source.denx.de/u-boot/u-boot
# * https://git.beagleboard.org/beagleboard/u-boot.git
#
MIRROR_UBOOT="https://gitlab.com/u-boot/u-boot.git"
UBOOT_BUILD_NAME="code-uboot"

#
# Kernel.
#
# * https://github.com/RobertCNelson/bb-kernel
# * https://github.com/torvalds/linux
# * https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
#
MIRROR_KERNEL="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
KERNEL_BUILD_NAME="code-kernel"

#
# Root File System.
#
# * https://rcn-ee.com/rootfs/eewiki/minfs/
#
MIRROR_FS="https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/armhf/"
RTFS_BUILD_NAME="src-rootfs"
